### PR TITLE
Corrected typos in nearly all of the HD library .lib files where

### PR DESCRIPTION
**Pull request by RTimothyEdwards**
Corrected typos in nearly all of the HD library .lib files where "related_ground_pin" had been set to "VNB" instead of "VGND" for six cells in the library (dlclkp_1, _2, and _4; and sdlclkp_1, _2, and _4).  This fixes part of the problem noted in https://github.com/google/skywater-pdk/issues/183 (the rest of that problem has already been patched in this fork of the repository).

### CODE REVIEW

**Comment by sifferman** [comment]
Thanks, @RTimothyEdwards! I am now using this fork but am still getting these errors:

```
Error: Line 82148, Cell 'sky130_fd_sc_hd__lpflow_lsbuf_lh_hl_isowell_tap_1', pg_pin 'VGND', An invalid attribute 'VNB' is found. (LBDB-27)
Error: Line 82282, Cell 'sky130_fd_sc_hd__lpflow_lsbuf_lh_hl_isowell_tap_2', pg_pin 'VGND', An invalid attribute 'VNB' is found. (LBDB-27)
Error: Line 82416, Cell 'sky130_fd_sc_hd__lpflow_lsbuf_lh_hl_isowell_tap_4', pg_pin 'VGND', An invalid attribute 'VNB' is found. (LBDB-27)
Error: Line 82693, Cell 'sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_tap_1', pg_pin 'VGND', An invalid attribute 'VNB' is found. (LBDB-27)
Error: Line 82827, Cell 'sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_tap_2', pg_pin 'VGND', An invalid attribute 'VNB' is found. (LBDB-27)
Error: Line 82961, Cell 'sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_tap_4', pg_pin 'VGND', An invalid attribute 'VNB' is found. (LBDB-27)
```

Any ideas? This is my `lc_shell` command:

```tcl
./skywater-pdk-libs-sky130_fd_sc_hd/timing/sky130_fd_sc_hd__tt_025C_1v80.lib
```

**Comment by RTimothyEdwards** [comment]
I guess I can keep fixing the problems as they show up.  I guess this error was shadowed by the previous errors?  This particular error is that the "related_bias_pin" entry got inserted by some automatic script for all power supply pins, except that the cells which do not have a separate bias pin (which is all the tap cells---not just the six output above, and I'm not sure why the other instances weren't caught) also got the same line inserted.

I will go ahead and fix these, too.  Keep the reports coming as long as there are still errors being reported.

**Comment by RTimothyEdwards** [comment]
@sifferman :  Those errors have now been fixed by PR #14.

I figured out the answer to my query above about why other instances weren't caught---it's because most of the tap cells don't appear in the .lib files at all;  they do not have signal connections and so they are not part of any timing checks.

**Comment by sifferman** [comment]
Thanks, @RTimothyEdwards! All `lc_shell` errors have been resolved!
```
read_lib ./skywater-pdk-libs-sky130_fd_sc_hd/timing/sky130_fd_sc_hd__tt_025C_1v80.lib
...   (lots of warnings) ...
Technology library 'sky130_fd_sc_hd__tt_025C_1v80' read successfully
1
write_lib sky130_fd_sc_hd__tt_025C_1v80 -format db -output library.db
Wrote the 'sky130_fd_sc_hd__tt_025C_1v80' library to 'library.db' successfully
1
```
[lc_output.txt](https://github.com/efabless/skywater-pdk-libs-sky130_fd_sc_hd/files/13589574/lc_output.txt)

But now when I pass the exported .db file to `dc_shell-t`, I get
```
read_file -format ddc library.db
Loading db file '/tools/synopsys/syn/S-2021.06-SP1/libraries/syn/gtech.db'
Loading db file '/tools/synopsys/syn/S-2021.06-SP1/libraries/syn/standard.sldb'
  Loading link library 'gtech'
Reading ddc file '/home/ethan/GitHub/schematics/design_compiler/library.db'.
Error: DDC internal read error in file '/home/ethan/GitHub/schematics/design_compiler/library.db'. (DDC-4)
Loaded 0 designs.
```
[dc_output.txt](https://github.com/efabless/skywater-pdk-libs-sky130_fd_sc_hd/files/13589573/dc_output.txt)

Not a very helpful error, so it may just be an issue with my Synopsys install. If you get a chance, could you check if you get this error too?

Thanks!

**Comment by RTimothyEdwards** [comment]
I don't know how to run the Synopsys tools, myself.  Maybe @marwaneltoukhy could test it?

**Comment by RTimothyEdwards** [comment]
@sifferman :  Does it have anything to do with the fact that `lc_output.txt` says `wrote_lib ... -format db` but `dc_output.txt` has `read_file -format ddc`?

**Comment by sifferman** [comment]
Whoops, thanks! All issues have been resolved

(Here is my full build script for future reference: https://github.com/sifferman/schematics/tree/main/design_compiler)

**Pull request merged**
